# Generated by Django 3.2.12 on 2022-02-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('Romance', 'Romance'), ('Sci-Fi', 'Sci-fi'), ('Fantasy', 'Fantacy'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Westerns', 'Westerns')], default=True, max_length=355),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
